== Preparing for the workshop

You need to have your laptop with a modern browser and your favorite code editor installed. During the course, there are several code demos. I put both the code example within this book and on Codepen as live demo. You can find those live demos in the following Codpen collection. Please fork them and play around the code yourself. You won’t learn it until you hack it.

http://codepen.io/collection/XdbWMW/[Code examples on CodePen]

=== -prefix-free library

http://leaverou.github.io/prefixfree/[-prefix-free] is the JS library made by http://lea.verou.me/[Lea Verou]. It parses the CSS properties and apply centain vendor prefixes on the rules by determing the browser version. This library allows us to stop worrying about different prefixes and old syntaxes.

=== Preprocessor

The logic in SCSS preprocessor provides us the DRY—Don’t repeat yourself—way to write the CSS code. We will use some SCSS code when defining the grid layout. If you are using other preprocessor, you may find their equivalents in http://csspre.com[CSSPre.com]. If you aren’t using any preprocessor, no worry, we also provide the full CSS code.

In the CodePen demos, you can also view the CSS by clicking on the `compiled` button in the SCSS panel. 

